chore(engine): マップデータが更新されてもセーブデータが残るように仕様変更
WWAWing/WWAWing pull request #299
Opened 2020-09-13 05:28 UTC by aokashi

Quick Save のセーブデータが残るように仕様を変更します。

セーブデータが残る条件は、セーブ時のワールド名 (WWAData.worldName) が現在プレイしているマップデータのワールド名と一致しているかとなります。

ロードポリシー ( #257 ) がまだはっきりしていないので、「この比較方法がいい」とありましたらご意見が欲しいです。

2020-10-17 11:25 UTC, aokashi commented
セーブデータが消えたとメッセージ表記はあっても、内部的にはセーブデータが無効になっただけだから、セーブデータを全部埋めない限り起動の度に毎回メッセージは来るんだなあ。

2020-11-01 05:43 UTC, aokashi commented
@matsuyuki-a 実装が終わりましたのでレビューの方お願いします。 🙇‍♂️ 
( #301 の件もありますが、本ブランチ関係なくても発生するので今のところ無視する形で進めます )

2020-11-02 16:20 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +        disAllowLoadOldSave: boolean = false,
`disallowLoadOldSave` でお願いします。disallow で1単語です。

2020-11-02 16:22 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                    alert("これまで保存したセーブデータはワールド名の変更やロードポリシーの変更に伴い、消えてしまいました。");
「ロードポリシー」という単語を使うよりは、それが何なのか、プレイヤーがわかりやすいようにすべきかなと思います。

2020-11-02 16:23 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +    const disAllowLoadOldSave = (() => {
https://github.com/WWAWing/WWAWing/pull/299/files#r516088546

2020-11-02 16:24 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +    private static DoNotAnything = () => {};
FYI: 何もしない関数は,  `noop` という便利な表現があります

2020-11-02 16:25 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +    private static DoNotAnything = () => {};
lowerCammelCase にした方が誤解をまねかないかな

2020-11-02 16:26 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +    private indexDBOpen(): IDBOpenDBRequest {
👍

2020-11-02 16:29 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +                        failedLoadingSaveDataIds.push(i);
可能なら、この条件分岐はDB保存ロジックの奥深くに入れるよりは、
wwa_main側というか、アプリケーション側にあったほうがよいと思います。

wwa_save の責務は、DB保存に関わる操作に徹したいです。

2020-11-02 16:30 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +                        failedLoadingSaveDataIds.push(i);
（IE専用コードでこのへんのロジックをコピるのが事故りそう cf: #301 ）

2020-11-05 08:51 UTC, aokashi commented on packages/engine/src/wwa_main.ts
> +                    alert("これまで保存したセーブデータはワールド名の変更やロードポリシーの変更に伴い、消えてしまいました。");
```
これまで保存したセーブデータは、マップデータのワールド名の変更やマップデータ制作者が設定した仕様が原因により、消えてしまいました。
```

ロードポリシーという単語を使わないとこうなるのかなと思います。

2020-11-05 08:53 UTC, aokashi commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +    private static DoNotAnything = () => {};
あれ、 static な要素だと UpperCamelCase が普通なのかと思ったんですが、間違いでしたか・・・。
直しておきます。

2020-11-05 08:55 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                    alert("これまで保存したセーブデータはワールド名の変更やロードポリシーの変更に伴い、消えてしまいました。");
どちらの理由で失敗したかを明確にできないかな...?
`hasFailedLoadingSaveData` という boolean 値にするより、エラーコードを返すみたいな感じで

2020-11-05 08:55 UTC, aokashi commented on packages/engine/src/wwa_main.ts
> +                    alert("これまで保存したセーブデータはワールド名の変更やロードポリシーの変更に伴い、消えてしまいました。");
それ今さっき思ったのでその方法で検討してみます。

2020-11-05 08:56 UTC, aokashi commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +                        failedLoadingSaveDataIds.push(i);
条件分岐部分をコールバックメソッドにしてしまって、 WWASave のコンストラクターの引数に充てるように検討してみます。

2020-11-05 11:03 UTC, aokashi commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータ制作者が設定した仕様";
これ単純に「マップデータの内容変更」だけで済ませてもいいような気がする

2020-11-05 11:03 UTC, aokashi commented on packages/engine/src/wwa_main.ts
> +    private _checkSaveDataCompatibility(saveDataWorldName: string, saveDataHash: string): FailedLoadingSaveDataCause {
今回は wwa_main に置いたけど、 #68 の件もあるので別の場所の移行も検討しておきたいかな

2020-11-05 11:03 UTC, aokashi commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +                        if (failedLoadingSaveDataCauses.indexOf(failedCause) === -1) {
ネストが深くなっているので、もうちょっと単純にしてもいいような気がする

2020-11-08 13:58 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/index.ts
> +import WWASave, { FailedLoadingSaveDataCause, OnCheckLoadingSaveDataFunction, OnCompleteLoadingSaveDataFunction } from './WWASave';
default import とそれ以外が混在しているのが若干わかりにくいかなと思うのですが、wwa_save 全体に言えることなので、今後検討します。

2020-11-11 14:24 UTC, aokashi commented on packages/engine/src/wwa_save/index.ts
> +import WWASave, { FailedLoadingSaveDataCause, OnCheckLoadingSaveDataFunction, OnCompleteLoadingSaveDataFunction } from './WWASave';
前から思っていたけど、 type の場合は1つ1つ別ファイルに独立すべきか、関連しているファイルに置くべきなのか、はっきりしていないようですが・・・？

2020-11-11 15:55 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/index.ts
> +import WWASave, { FailedLoadingSaveDataCause, OnCheckLoadingSaveDataFunction, OnCompleteLoadingSaveDataFunction } from './WWASave';
モジュールの取り扱いについて、コーディング規約かが必要そうですね

2020-12-13 06:17 UTC, matsuyuki-a commented on packages/engine/src/wwa_save/WWASaveDataDBList.ts
> +                let failedLoadingSaveDataCauses = [];
空配列を代入して、型注釈なしだと、 `any[]` になってしまうので、型注釈をつけた方がよいと思います。

また、
``` ts
let failedLoadingSaveData: { id: number; cause: OnCheckLoadingSaveDataFunction = [];
```
のように、id と 失敗理由をセットにしたオブジェクトで扱った方が構造化されていてわかりやすいと思います。

2020-12-13 06:25 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
若干冗長かもしれないですが、4つあるセーブデータのどれが消えたかを示せると望ましい？

2020-12-13 06:26 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                        }
今後条件が増えたときのために、 "DISALLOW_OLD_SAVE_DATA" の場合も `break;` があるとよいと思います

2020-12-13 06:29 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
複数、同じ理由で消えたセーブデータがあるときに若干冗長になってしまうので、次のどちらかにしたいです

- 同じ理由による削除表示は1回に留める
- 4つあるセーブデータの内どれが消えたかをあわせて示す

2020-12-13 06:34 UTC, aokashi commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
`failedLoadingSaveDataCauses` は事前に同じ理由がある場合は削除するように WWASaveDataDBList で行っているので、同じ理由で消えたセーブデータが複数あっても、表示されるメッセージは1つだけになると思います。
https://github.com/WWAWing/WWAWing/blob/feb793faa7124eb8143490dc9bda41ec58f9a887/packages/engine/src/wwa_save/WWASaveDataDBList.ts#L261

2020-12-13 06:49 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
お、そうなんですね、そうすると、

- メッセージを1つにするという仕様がどこかに書いてあるとよい
- メッセージを1つにする処理が若干わかりにくいので、次のようにするときれいにできます

``` ts
this.onCompleteLodingSaveData([...new Set(failedLoadingSaveDataCauses)])
```

2020-12-13 06:49 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
Set は IE11でも使えるのと、spread operator (`...`) はTypeScriptのコンパイル時に直されるので大丈夫なはず

2020-12-13 08:02 UTC, aokashi commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
Set は IE11 でも使用できるんですね。
(いずれにせよ、 #302 が完成しないとあまり意味はないように見えますが)

重複項目の削除は下記を参考にしていますが、スプレッド構文が使用できないのではと予測していて .filter で重複分を削除していた感じです。
https://qiita.com/piroor/items/02885998c9f76f45bfa0

2020-12-13 12:30 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
自分の認識がいろいろ軽率だったので追記します...
まず、 `...new Set(hoge)` を使うには `target: "es5"` を維持する場合は  tsconfig の `compilerOptions` に `"downlevelIteration": true` を、 "lib" に `dom.itarable` が必要でした。

そこまでだったら追加するだけでいいのですが、さらに、IE11 では `Set` のコンストラクタに配列を与えると正しい挙動にならないみたいですね。( https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/Set の　「ブラウザー実装状況」の「new Set(iterable)」「Internet Explorer」をみると「なし」になってます（どうしてこんなピンポイントな..., 開発者ツールで試しても確かに動きませんでした)

というわけで、このままのコードでよいと思います。処理がちょっとパッと見ただけだとわかりにくいので、コメントを残してもらえると助かります 🙇

2021-01-04 13:33 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                    let message = "これまで保存したセーブデータは、下記の理由により消えてしまいました。";
```suggestion
                    let message = "これまでに保存されていたセーブデータは、下記の理由により消えてしまいました。";
```

2021-01-04 13:33 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                    let message = "これまで保存したセーブデータは、下記の理由により消えてしまいました。";
細かいけど 🙇

2021-01-04 14:03 UTC, matsuyuki-a requested changes
試しにセーブしてからマップデータを変更してロードしようとしたらアラートが出ずに起動してしまいました。原因は調査中ですが、エラーコードの重複排除のコードが正しく動いていないようです。

2021-01-04 14:49 UTC, aokashi commented
> 
> 
> 試しにセーブしてからマップデータを変更してロードしようとしたらアラートが出ずに起動してしまいました。(セーブデータはちゃんと消えてくれましたが）
> 
> 原因は調査中ですが、エラーコードの重複排除のコードが正しく動いていないようです。

こっちでも試してみたんですが、逆にアラート表示時にエラー内容が消えたセーブデータの数だけ表示されていました。
確かめたところ、 `filter` の条件が逆だったので修正しましたが、これでアラートは正常に表示されるでしょうか？

2021-01-04 14:54 UTC, matsuyuki-a commented
みます

2021-01-04 14:57 UTC, matsuyuki-a commented
アラート出ること確認できました！

2021-01-04 15:05 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータのワールド名の変更";
```suggestion
                                message += "\n・制作者によるマップデータのワールド名の変更";
```

2021-01-04 15:06 UTC, matsuyuki-a commented on packages/engine/src/wwa_main.ts
> +                                message += "\nマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
```suggestion
                                message += "\n・制作者によるマップデータの内容変更 (マップデータ制作者の設定により、内容が変更されるとセーブデータが消去されます)";
```

2021-01-04 15:09 UTC, matsuyuki-a approved these changes
アラートの文言だけちょっと気になったので変更を提案させていただきましたが、直してもらったら確認不要でマージして大丈夫ですー

2021-01-05 00:04 UTC, merged